# Generated by Django 2.2 on 2019-07-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_id", models.IntegerField(unique=True)),
                ("source", models.CharField(max_length=11, null=True)),
                ("destination", models.CharField(max_length=11, null=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField(null=True)),
            ],
        )
    ]
